export const CONSTANTS = Object.freeze({
  LINKEDIN: 'https://www.linkedin.com/company/69560619/',
  TWITTER: 'https://twitter.com/xata',
  EMAIL: 'mailto:info@xata.io',
  DISCORD: 'https://xata.io/discord',
  NAV: {
    ABOUT: 'https://xata.io/about',
    AI: 'https://xata.io/chatgpt',
    BLOG: 'https://xata.io/blog',
    CAREERS: 'https://xata.io/careers',
    DOCS: 'https://xata.io/docs/',
    FEATURES: 'https://xata.io/features',
    GALLERY: '/',
    HOME: 'https://xata.io/',
    LOGIN: '/login',
    PRICING: 'https://xata.io/pricing',
    SUPPORT: 'https://support.xata.io/',
    START_BUILDING: 'https://app.xata.io/signin',
    XATA: 'https://xata.io',
  },
  LEGAL: {
    COOKIES: 'https://xata.io/#',
    TERMS: 'https://xata.io/terms-of-use',
    PRIVACY_POLICY: 'https://xata.io/privacy',
  },
});

export const COLORS = Object.freeze({
  alienArmpit: '#73d000',
  malachite: '#00cc59',
  munsellGreen: '#00c080',
  tiffanyBlue: '#00bda6',
  irisBlue: '#00bbd6',
  vividCerulean: '#00a8eb',
  blueDeFrance: '#3582f8',
  veryLightBlue: '#6862f3',
  lavenderBlue: '#9353f9',
  lavender: '#b144fa',
  phlox: '#e612f1',
  fluorescentPink: '#f8149a',
  folly: '#ff005d',
});
