export const CONSTANTS = Object.freeze({
  LINKEDIN: 'https://www.linkedin.com/company/69560619/',
  TWITTER: 'https://twitter.com/xata',
  EMAIL: 'mailto:info@xata.io',
  DISCORD: 'https://xata.io/discord',
  NAV: {
    ABOUT: 'https://xata.io/about',
    AI: 'https://xata.io/chatgpt',
    BLOG: 'https://xata.io/blog',
    CAREERS: 'https://xata.io/careers',
    DOCS: 'https://xata.io/docs/',
    FEATURES: 'https://xata.io/features',
    HOME: 'https://xata.io/',
    LOGIN: 'http://app.xata.io/',
    PRICING: 'https://xata.io/pricing',
    SUPPORT: 'https://support.xata.io/',
    START_BUILDING: 'https://app.xata.io/signin',
    XATA: 'https://xata.io',
  },
  LEGAL: {
    COOKIES: 'https://xata.io/#',
    TERMS: 'https://xata.io/terms-of-use',
    PRIVACY_POLICY: 'https://xata.io/privacy',
  },
});
