import { Footer } from '@/components/Footer';

import '../globals.css';
import '../../tailwind.css';

export const metadata = {
  title: 'Made with Xata',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
