import { Footer } from '@/components/Footer';
import { LoggedInBar } from '@/components/LoggedInBar';

import '../globals.css';
import '../../tailwind.css';

export const metadata = {
  title: 'Made with Xata',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <LoggedInBar
          buttonLabel="Edit"
          buttonLink="#"
          user={{
            name: 'John Doe',
            avatar: '',
            avatarColor: 'alienArmpit',
          }}
        />
        <Footer />
      </body>
    </html>
  );
}
